name: test_task_privat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  sqflite: ^2.3.2
  equatable: ^2.0.5
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  freezed: ^2.4.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  go_router: ^13.1.0
  firebase_core: ^2.25.2
  firebase_dynamic_links: ^5.4.11
  flutter_dotenv: ^5.0.0
  path: ^1.8.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
